name: Release
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Get latest ripgrep release
        id: latest_ripgrep_release
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{owner}/{repo}/releases/latest
          owner: BurntSushi
          repo: ripgrep
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Get latest zeebonk/ripgrep-docker releases from Dockerhub
        uses: boyeborg/fetch-url-action@v1.1
        id: latest_dockerhub_releases
        with:
          url: https://hub.docker.com/v2/repositories/zeebonk/ripgrep-docker/tags/?page_size=100&page=1&ordering=last_updated
      -
        run: 'false'
        if: contains(fromJson(steps.latest_dockerhub_releases.outputs.data).results.*.name, fromJson(steps.latest_ripgrep_release.outputs.data).name)
      -
        name: Check-out repo
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: zeebonk/ripgrep-docker:test
          build-args: |
            RIPGREP_VERSION=${{ fromJson(steps.latest_ripgrep_release.outputs.data).name }}
            DEBIAN_VERSION=stable-slim
            RUST_VERSION=1-slim
