name: Release
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repo
        uses: actions/checkout@v2
      - name: Build container
        run: docker build -t ripgrep-docker:12.1.1 --build-arg RIPGREP_VERSION=12.1.1 .
